// generated by stringer -type=StructuredMethod; DO NOT EDIT

package proto

import "fmt"

const _StructuredMethod_name = "CreateTableGetTableRowPutTableRowConditionalPutTableRowIncrementTableRowDeleteTableRowDeleteTableRowRangeScanTableBatchTable"

var _StructuredMethod_index = [...]uint8{0, 11, 22, 33, 55, 72, 86, 105, 114, 124}

func (i StructuredMethod) String() string {
	if i < 0 || i >= StructuredMethod(len(_StructuredMethod_index)-1) {
		return fmt.Sprintf("StructuredMethod(%d)", i)
	}
	return _StructuredMethod_name[_StructuredMethod_index[i]:_StructuredMethod_index[i+1]]
}
